apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
spec:
  containers:
    - name: jenkins
      image: jenkins
      volumeMounts:
      - mountPath: "/var/jenkins_home"
        name: jenkins
  volumes:
    - name: jenkins
      persistentVolumeClaim:
        claimName: test-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc                
spec:
  accessModes:
    - ReadWriteOnce             
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi              
  storageClassName: "" 

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 1Gi                
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce              
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: ""
  nfs:
    server: 10.1.11.9
    path: /home/nfs



