apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: http-go
  labels:
    app: http-go
spec:
  replicas: 6
  selector:
    matchLabels:
      app: http-go
  template:
    metadata:
      labels:
        app: http-go
    spec:
      containers:
      - name: http-go
        image: healinyoon/http-go
        ports:
        - containerPort: 8080
