apiVersion: v1
kind: ReplicationController
metadata:
  name: http-go
spec:
  replicas: 3
  selector:
    app: http-go
  template:
    metadata:
      name: http-go
      labels:
        app: http-go  # 위의 selector의 app과 동일해야함
    spec:
      containers:
      - name: http-go
        image: healinyoon/http-go
        ports:
        - containerPort: 8080