# label 수정해보기
apiVersion: v1
kind: Pod
metadata:
  name: http-go-v2  # 이름이 겹치면 안됨
  labels:
    creation_method: manual-v2
spec:
  containers:
  - name: http-go
    image: healinyoon/http-go
    ports:
    - containerPort: 8080
      protocol: TCP
